playerid_mapping = "playerid_mapping.pkl"
teamid_mapping = "teamid_mapping.pkl"
targets_artifact = "train_targets.pkl"
scores1_mean_artifact = "train_scores1_mean.pkl"
scores2_mean_artifact = "train_scores2_mean.pkl"
scores3_mean_artifact = "train_scores3_mean.pkl"
scores4_mean_artifact = "train_scores4_mean.pkl"
scores5_mean_artifact = "train_scores5_mean.pkl"
team_scores1_mean_artifact = "train_team_scores1_mean.pkl"
team_scores2_mean_artifact = "train_team_scores2_mean.pkl"
team_scores3_mean_artifact = "train_team_scores3_mean.pkl"

scores1_last_artifact = "train_scores1_last.pkl"
scores2_last_artifact = "train_scores2_last.pkl"
scores3_last_artifact = "train_scores3_last.pkl"
scores4_last_artifact = "train_scores4_last.pkl"
scores5_last_artifact = "train_scores5_last.pkl"
team_scores1_last_artifact = "train_team_scores1_last.pkl"
team_scores2_last_artifact = "train_team_scores2_last.pkl"
team_scores3_last_artifact = "train_team_scores3_last.pkl"

scores1_first_artifact = "train_scores1_first.pkl"
scores2_first_artifact = "train_scores2_first.pkl"
scores3_first_artifact = "train_scores3_first.pkl"
scores4_first_artifact = "train_scores4_first.pkl"
scores5_first_artifact = "train_scores5_first.pkl"
team_scores1_first_artifact = "train_team_scores1_first.pkl"
team_scores2_first_artifact = "train_team_scores2_first.pkl"
team_scores3_first_artifact = "train_team_scores3_first.pkl"

team_standings_artifact = "train_team_standings.pkl"
awards_artifact = "train_awards.pkl"
transactions_artifact = "train_transactions.pkl"
player_twitter_artifact = "train_pltwitter.pkl"
rosters_artifact = "train_rosters.pkl"
event_artifact = "train_events.pkl"

TARGETS = ["target1", "target2", "target3", "target4"]
SCORES1 = ["home", "jerseyNum", "positionCode", "positionType", "battingOrder"]
SCORES2 = [
    "flyOuts",
    "groundOuts",
    "runsScored",
    "doubles",
    "triples",
    "homeRuns",
    "strikeOuts",
    "baseOnBalls",
    "intentionalWalks",
    "hits",
    "hitByPitch",
    "atBats",
    "caughtStealing",
    "stolenBases",
    "groundIntoDoublePlay",
    "groundIntoTriplePlay",
    "plateAppearances",
    "totalBases",
    "rbi",
    "leftOnBase",
    "sacBunts",
    "sacFlies",
    "catchersInterference",
    "pickoffs",
]
SCORES3 = [
    "gamesPlayedBatting",
    "gamesPlayedPitching",
    "gamesStartedPitching",
    "completeGamesPitching",
    "shutoutsPitching",
    "winsPitching",
    "lossesPitching",
    "saveOpportunities",
    "saves",
    "holds",
    "blownSaves",
]
SCORES4 = [
    "flyOutsPitching",
    "airOutsPitching",
    "groundOutsPitching",
    "runsPitching",
    "doublesPitching",
    "triplesPitching",
    "homeRunsPitching",
    "strikeOutsPitching",
    "baseOnBallsPitching",
    "intentionalWalksPitching",
    "hitsPitching",
    "hitByPitchPitching",
    "atBatsPitching",
    "caughtStealingPitching",
    "stolenBasesPitching",
]
SCORES5 = [
    "inningsPitched",
    "earnedRuns",
    "battersFaced",
    "outsPitching",
    "pitchesThrown",
    "balls",
    "strikes",
    "hitBatsmen",
    "balks",
    "wildPitches",
    "pickoffsPitching",
    "rbiPitching",
    "inheritedRunners",
    "inheritedRunnersScored",
    "catchersInterferencePitching",
    "sacBuntsPitching",
    "sacFliesPitching",
    "assists",
    "putOuts",
    "errors",
    "chances",
]
AWARDS = ["awardId"]
ROSTERS = ["statusCode", "teamId"]
TRANSACTIONS = ["typeCode", "toTeamId", "fromTeamId"]
PLTWITTER = ["numberOfFollowers"]

TEAM_SCORES1 = [
    "flyOuts",
    "groundOuts",
    "runsScored",
    "doubles",
    "triples",
    "homeRuns",
    "strikeOuts",
    "baseOnBalls",
    "intentionalWalks",
    "hits",
    "hitByPitch",
    "atBats",
    "caughtStealing",
    "stolenBases",
    "groundIntoDoublePlay",
    "groundIntoTriplePlay",
    "plateAppearances",
    "totalBases",
    "rbi",
    "leftOnBase",
    "sacBunts",
    "sacFlies",
    "catchersInterference",
    "pickoffs",
]
TEAM_SCORES2 = [
    "airOutsPitching",
    "groundOutsPitching",
    "runsPitching",
    "doublesPitching",
    "triplesPitching",
    "homeRunsPitching",
    "strikeOutsPitching",
    "baseOnBallsPitching",
    "intentionalWalksPitching",
    "hitsPitching",
    "hitByPitchPitching",
    "atBatsPitching",
    "caughtStealingPitching",
    "stolenBasesPitching",
]
TEAM_SCORES3 = [
    "inningsPitched",
    "earnedRuns",
    "battersFaced",
    "outsPitching",
    "hitBatsmen",
    "balks",
    "wildPitches",
    "pickoffsPitching",
    "rbiPitching",
    "inheritedRunners",
    "inheritedRunnersScored",
    "catchersInterferencePitching",
    "sacBuntsPitching",
    "sacFliesPitching",
]
TEAM_STANDINGS = [
    "divisionRank",
    "leagueRank",
    "wildCardRank",
    "leagueGamesBack",
    "sportGamesBack",
    "divisionGamesBack",
    "wins",
    "losses",
    "pct",
    "runsAllowed",
    "runsScored",
    "divisionChamp",
    "divisionLeader",
    "wildCardLeader",
    "eliminationNumber",
    "wildCardEliminationNumber",
    "homeWins",
    "homeLosses",
    "awayWins",
    "awayLosses",
    "lastTenWins",
    "lastTenLosses",
    "extraInningWins",
    "extraInningLosses",
    "oneRunWins",
    "oneRunLosses",
    "dayWins",
    "dayLosses",
    "nightWins",
    "nightLosses",
    "grassWins",
    "grassLosses",
    "turfWins",
    "turfLosses",
    "divWins",
    "divLosses",
    "alWins",
    "alLosses",
    "nlWins",
    "nlLosses",
    "xWinLossPct",
]

EVENT_COLS = [
    "gameType",
    "pitcherTeamId",
    "pitcherId",
    "hitterTeamId",
    "hitterId",
    "pitcherHand",
    "batSide",
    "launchSpeed",
    "launchAngle",
    "totalDistance",
    "startSpeed",
    "endSpeed",
    "spinRate",
    "spinDirection",
    "event",
    "inning",
    "halfInning",
    "homeScore",
    "awayScore"
]

GAME_TYPE_MAP = {
    'R': 1, 'F': 2, 'D': 3, 'L': 4, 'W': 5
}

EVENTDESC_MAP = {
    'Balk': 17,
    'Injury': 1,
    'Ejection': 2,
    'Pickoff 1B': 3,
    'Runner Out': 4,
    'Wild Pitch': 5,
    'Passed Ball': 6,
    'Defensive Sub': 7,
    'Game Advisory': 8,
    'Stolen Base 2B': 9,
    'Stolen Base 3B': 10,
    'Pitch Challenge': 11,
    'Defensive Indiff': 12,
    'Defensive Switch': 13,
    'Pickoff Error 1B': 14,
    'Pitching Substitution': 15,
    'Offensive Substitution': 16,
    'None': 0,
    'Walk': 18,
    'Double': 19,
    'Flyout': 20,
    'Single': 21,
    'Triple': 22,
    'Lineout': 23,
    'Pop Out': 24,
    'Forceout': 25,
    'Home Run': 26,
    'Sac Bunt': 27,
    'Groundout': 28,
    'Double Play': 29,
    'Field Error': 30,
    'Intent Walk': 31,
    'Hit By Pitch': 32,
    'Grounded Into DP': 33,
    'Caught Stealing 2B': 34,
    'Sac Fly': 35,
    'Catcher Interference': 36,
    'Strikeout': 37,
    'Fielders Choice Out': 38,
    'Umpire Substitution': 39,
    'Bunt Groundout': 40,
    'Fielders Choice': 41,
    'Strikeout Double Play': 42,
    'Stolen Base Home': 43,
    'Bunt Pop Out': 44,
    'Pickoff Error 2B': 45,
    'Batter Interference': 46,
    'Caught Stealing 3B': 47,
    'Other Advance': 48,
    'Pickoff Caught Stealing 2B': 49,
    'Caught Stealing Home': 50,
    'Bunt Lineout': 51,
    'Pickoff 2B': 52,
    'Error': 53,
    'Pickoff Caught Stealing Home': 54,
    'Fan Interference': 55,
    'Triple Play': 56,
    'Sac Fly Double Play': 57,
    'Pickoff 3B': 58,
    'Pickoff Caught Stealing 3B': 59,
    'Sac Bunt Double Play': 60,
    'Pitcher Switch': 61,
    'Pickoff Error 3B': 62,
    'Runner Placed On Base': 63
}

AWARDID_DICT = {
    "MILBORGAS": 1,
    "FSLMSAS": 2,
    "MWLMSAS": 3,
    "SLMSAS": 4,
    "TLMSAS": 5,
    "ELMSAS": 6,
    "MEXMSAS": 7,
    "SALMSAS": 8,
    "CARMSAS": 9,
    "AFLRS": 10,
    "CALMSAS": 11,
    "FUTURES": 12,
    "ALPBMSAS": 13,
    "DSLMSAS": 14,
    "ILMSAS": 15,
    "WSCHAMP": 16,
    "ALAS": 17,
    "PCLMSAS": 18,
    "NLAS": 19,
    "ALPOW": 20,
    "NORMSAS": 21,
    "NLPOW": 22,
    "PIOLGAS": 23,
    "NYPMSAS": 24,
    "BAMLART": 25,
    "TEXPOWP": 26,
    "CALPOWP": 27,
    "INTPOWP": 28,
    "TEXPOWH": 29,
    "FSLPOWP": 30,
    "CARPOWH": 31,
    "MIDPOWH": 32,
    "MIDPOWP": 33,
    "FSLPOWH": 34,
    "CALPOWH": 35,
    "PCLPOWP": 36,
    "PCLPOWH": 37,
    "INTPOWH": 38,
    "SALPOWH": 39,
    "CARPOWP": 40,
    "SALPOWP": 41,
    "EASPOWH": 42,
    "EASPOWP": 43,
    "SOUPOWH": 44,
    "SOUPOWP": 45,
    "MLBPLAYOW": 46,
    "FSLPSAS": 47,
    "CSAS": 48,
    "MLBAFIRST": 49,
    "MLBSECOND": 50,
    "SLPSAS": 51,
    "BAMILAS": 52,
    "BADSLAS": 53,
    "BAHAXXAS": 54,
    "TLPSAS": 55,
    "BALAXXAS": 56,
    "BAAAXAS": 57,
    "BAROAS": 58,
    "BAAAAAS": 59,
    "BASSAS": 60,
    "SALPSAS": 61,
    "APPPSAS": 62,
    "NLGG": 63,
    "CALPSAS": 64,
    "NWLPSAS": 65,
    "PIOPSAS": 66,
    "AZLPSAS": 67,
    "ALGG": 68,
    "ELPSAS": 69,
    "NLSS": 70,
    "CARPSAS": 71,
    "MWLPSAS": 72,
    "ALSS": 73,
    "DSLPSAS": 74,
    "GCLPSAS": 75,
    "ILPSAS": 76,
    "PCLPSAS": 77,
    "PWLPSAS": 78,
    "ALPBEOSAS": 79,
    "NYPPOWP": 80,
    "APPPOWH": 81,
    "NORPOWH": 82,
    "APPPOWP": 83,
    "PIOPOWH": 84,
    "NORPOWP": 85,
    "AFLPSAS": 86,
    "NYPPOWH": 87,
    "PIOPOWP": 88,
    "MILBGG": 89,
    "WDPOY": 90,
    "MLBHOF": 91,
    "HRDERBY": 92,
    "NLPOM": 93,
    "NLRRELMON": 94,
    "ALROM": 95,
    "NLROM": 96,
    "ALPITOM": 97,
    "ALPOM": 98,
    "NLPITOM": 99,
    "ALRRELMON": 100,
    "ALPBPLOM": 101,
    "SOUPOM": 102,
    "ALPBPIOM": 103,
    "CARPOM": 104,
    "INTPOM": 105,
    "CALPOM": 106,
    "EASPOM": 107,
    "PCLPOM": 108,
    "SALPOM": 109,
    "MIDPOM": 110,
    "TEXPOM": 111,
    "FSLPOM": 112,
    "AFLPOWP": 113,
    "AFLPOWH": 113,
    "LMPMOY": 113,
    "VWLRLOY": 113,
    "NYPPOM": 113,
    "APPPOM": 113,
    "PWLROY": 113,
    "VWLPOY": 113,
    "PWLCPOY": 113,
    "VWLOPOY": 113,
    "VWLCPOY": 113,
    "LMPPOY": 113,
    "AZLPOM": 113,
    "SEAMVP": 113,
    "PWLMVP": 113,
    "VWLROY": 113,
    "VWLMOY": 113,
    "FSLCOY": 113,
    "NORPOM": 113,
    "PIOPOM": 113,
    "LMPMVP": 113,
    "PWLMOY": 113,
    "GCLPOM": 113,
    "LMPROY": 113,
    "PWLPOY": 113,
    "NLCY": 113,
    "ALCPOY": 113,
    "ALROY": 113,
    "RETIREDUNI_116": 113,
    "NLCPOY": 113,
    "DSLPOY": 113,
    "MEXPSMVP": 113,
    "TEXROY": 113,
    "WSMVP": 113,
    "DWLPOY": 113,
    "MEXMVP": 113,
    "MLBPCALOR": 113,
    "DWLMVP": 113,
    "MLBPCNLCOM": 113,
    "MLBPCALOP": 113,
    "PIOPOY": 113,
    "NLMVP": 113,
    "TEXGOODGUY": 113,
    "NLCSMVP": 113,
    "DWLMOY": 113,
    "SFNWMA": 113,
    "TEXWORKINGMAN": 113,
    "MLBPCALCOM": 113,
    "NLMOY": 113,
    "ALPG": 113,
    "DHOY": 113,
    "NLPG": 113,
    "ALHAA": 113,
    "VWLMVP": 113,
    "LOUBROCK": 113,
    "CALMVP": 113,
    "MLBPCNLOR": 113,
    "AFLHOF": 113,
    "MLBPCPOY": 113,
    "MLBRC": 113,
    "MLBPCNLPIT": 113,
    "NLREL": 113,
    "ALREL": 113,
    "MLBPCNLOP": 113,
    "NLROY": 113,
    "ALCY": 113,
    "ALCSMVP": 113,
    "MLBPCALPIT": 113,
    "CSMVP": 113,
    "BABERUTH": 113,
    "BAMLROY": 113,
    "MLBPCMOY": 113,
    "BAMLPOY": 113,
    "TEXMVP": 113,
    "ALMVP": 113,
    "DWLROY": 113,
    "ALMOY": 113,
    "NLHAA": 113,
    "WSCHAMPMGR": 113,
    "TEXHEARTHUSTLE": 113,
    "COLHEARTHUSTLE": 113,
    "ALPBPIOY": 113,
    "BAPOY": 113,
    "BAMMILBSCBRK": 113,
    "TLTOPS": 113,
    "BOSROY": 113,
    "BALHEARTHUSTLE": 113,
    "AFLSPORT": 113,
    "FUTMVP": 113,
    "MEXMOY": 113,
    "SLBUTL": 113,
    "CINMVP": 113,
    "CINHEARTHUSTLE": 113,
    "MWLTOPS": 113,
    "MILHEARTHUSTLE": 113,
    "ARIPOY": 113,
    "PIPELINEPOY": 113,
    "CHNHEARTHUSTLE": 113,
    "PIOTOPS": 113,
    "BAMMILBFCRP": 113,
    "MILMVP": 113,
    "SLMOY": 113,
    "PCLMVP": 113,
    "FLACONINE": 113,
    "ELPOY": 113,
    "HOUKILE": 113,
    "KCAHEARTHUSTLE": 113,
    "BOSSPIRIT": 113,
    "MILPOY": 113,
    "FSLMVPI": 113,
    "AZLMOY": 113,
    "PITHEARTHUSTLE": 113,
    "MINGOODGUY": 113,
    "SDGMVP": 113,
    "ILMVPI": 113,
    "PIPELINEHOY": 113,
    "CARMOY": 113,
    "APPMOY": 113,
    "CLETOMAHAWK": 113,
    "CHAHEARTHUSTLE": 113,
    "FLAROY": 113,
    "RETIREDUNI_143": 113,
    "SLCSMVP": 113,
    "SOUAVGTITLE": 113,
    "CLEMANOY": 113,
    "ARIROY": 113,
    "PHIHEARTHUSTLE": 113,
    "MEXPOY": 113,
    "CALTOPS": 113,
    "FSLTOPS": 113,
    "MILBHRAFX": 113,
    "FSLMVP": 113,
    "HOUROY": 113,
    "SFNHEARTHUSTLE": 113,
    "FLAHEARTHUSTLE": 113,
    "HOUHEARTHUSTLE": 113,
    "ANAHEARTHUSTLE": 113,
    "BOSMVP": 113,
    "FSLMOY": 113,
    "MINHEARTHUSTLE": 113,
    "TLPIOY": 113,
    "PIOMVP": 113,
    "NWLMVP": 113,
    "ASMVP": 113,
    "RETIREDUNI_140": 113,
    "SALMOP": 113,
    "TEXPOY": 113,
    "CALMOY": 113,
    "CLEGOODGUY": 113,
    "OAKCATFISH": 113,
    "MWLMOY": 113,
    "SEAHEARTHUSTLE": 113,
    "GCLMVP": 113,
    "MILGOODGUY": 113,
    "MWLPROY": 113,
    "LOUGEHRIG": 113,
    "MINPOHLAD": 113,
    "ELMVP": 113,
    "PCLTOPS": 113,
    "FLAMVP": 113,
    "BAMLMOY": 113,
    "NYAHEARTHUSTLE": 113,
    "SLTOPS": 113,
    "ELPMVP": 113,
    "CSMOY": 113,
    "ARIMVP": 113,
    "MILBHR": 113,
    "ILTOPS": 113,
    "BAMMILBSCOFF": 113,
    "DSLMOY": 113,
    "MILNEWCOMER": 113,
    "ELROY": 113,
    "NORTOPS": 113,
    "SLMVP": 113,
    "GCLMOY": 113,
    "CINPOY": 113,
    "SDGHEARTHUSTLE": 113,
    "ILMOY": 113,
    "TBAHEARTHUSTLE": 113,
    "HOUPOY": 113,
    "MILBHRAAX": 113,
    "BAMMILBSCRP": 113,
    "TONYCONIGLIARO": 113,
    "HRDERBYWIN": 113,
    "HUTCH": 113,
    "BALMVA": 113,
    "TLPLOY": 113,
    "MEXROY": 113,
    "NWLPOY": 113,
    "ELTOPS": 113,
    "TLCOY": 113,
    "ILROY": 113,
    "BAMMILBFCOFF": 113,
    "AFLRSMVP": 113,
    "CARTOPS": 113,
    "MEXCPOY": 113,
    "MIKECOOL": 113,
    "MINROOK": 113,
    "SALMVP": 113,
    "TORMVP": 113,
    "WARRENSPAHN": 113,
    "DETROY": 113,
    "AZLMVP": 113,
    "HEARTANDHUSTLE": 113,
    "MEXASMVP": 113,
    "ELMOY": 113,
    "DSLMVP": 113,
    "AAACMVP": 113,
    "MILBHRASX": 113,
    "PCLPOY": 113,
    "LMPFMVP": 113,
    "MEXREOY": 113,
    "SLBHUS": 113,
    "BAMMILBFCBRK": 113,
    "BAMMILBSCSP": 113,
    "MILHARRISON": 113,
    "ARIGOODGUY": 113,
    "TORMIP": 113,
    "NYNHEARTHUSTLE": 113,
    "MILBHRAAA": 113,
    "TLMOY": 113,
    "AFLMVP": 113,
    "CARMVP": 113,
    "SEAUNSUNG": 113,
    "TORPOY": 113,
    "BOSPOY": 113,
    "OAKSERVICE": 113,
    "STLHEARTHUSTLE": 113,
    "OAKHEARTHUSTLE": 113,
    "TORHEARTHUSTLE": 113,
    "CARPOY": 113,
    "WMLBDPOY": 113,
    "PCLROY": 113,
    "PIOMOY": 113,
    "CALROY": 113,
    "BOSMANOY": 113,
    "DETHEARTHUSTLE": 113,
    "ATLHEARTHUSTLE": 113,
    "USAMLPOY": 113,
    "TORROY": 113,
    "CINGOODGUY": 113,
    "ARIHEARTHUSTLE": 113,
    "CLEHEARTHUSTLE": 113,
    "LANHEARTHUSTLE": 113,
    "MINSIEBERT": 113,
    "FLAGOODGUY": 113,
    "MINPOY": 113,
    "SLMOP": 113,
    "SALCOY": 113,
    "SDGFIREMAN": 113,
    "BAMMILBFCSP": 113,
    "SALMOY": 113,
    "MINIMPROVED": 113,
    "BOSHEARTHUSTLE": 113,
    "ALPBPLOY": 113,
    "SALTOPS": 113,
    "ILMVP": 113,
    "SALMOMLP": 113,
    "MINMVP": 113,
    "NWLMOY": 113,
    "SDGCHAIRMAN": 113,
    "WASHEARTHUSTLE": 113,
    "SDGPOY": 113,
    "ALPBMOY": 113,
    "HOUMVP": 113,
    "APPPLOY": 113,
    "CALPOY": 113,
    "PWLFMVP": 113,
    "MINLEADER": 113,
    "NYPTOPS": 113,
    "RETIREDUNI_115": 113,
    "TORLEVEL": 113,
    "ALPBGG": 113,
    "RETIREDUNI_141": 113,
    "STLKILE": 113,
    "MLBLEGEND": 113,
    "BOSGOODGUY": 113,
    "SOUERATITLE": 113,
    "CALCOY": 113,
    "PCLMOY": 113,
    "RETIREDUNI_137": 113,
    "RETIREDUNI_142": 113,
    "APPPIOY": 113,
    "MILUNSUNG": 113,
    "MWLMVP": 113,
    "MLBPCCFA": 113,
    "RETIREDUNI_114": 113,
}
